### List all cars
GET http://localhost:3333/cars

### Get a particular message

GET http://localhost:3333/car/639f6ce9ab6f57e36272070b


### Update a car

PUT http://localhost:3333/car/639f6ce9ab6f57e36272070b


### Delete a car

DELETE http://localhost:3333/car/639f6cffab6f57e36272070d